SQL 1031: Add SQLTables edge case handling
mongodb/mongo-odbc-driver pull request #30
Opened 2022-10-24 17:49 UTC by bucaojit

Added MongoTableTypes struct to handle calls for `SQL_ALL_TABLE_TYPES`. 
Returning `ColIndexOutOfBounds` error when index is out of bounds. 
Added empty result response to SQL_ALL_SCHEMAS.

2022-10-27 20:03 UTC, nbagnard requested changes
Looking pretty good. I only have 2 comments and one of them being a small optimization.

2022-10-28 19:04 UTC, bucaojit commented on core/src/table_types.rs
> +            table_type: vec!["TABLE".to_string(), "VIEW".to_string()],
Sure, added the static const array.

2022-10-28 19:11 UTC, bucaojit commented on core/src/databases.rs
>      fn get_value(&self, col_index: u16) -> Result<Option<Bson>> {
I added the `row_index_is_valid` attribute in StatementHandle which gets set to true/false depending on the result of SQLFetch()->statement.next().  It gets checked in SQLGetData() before statement.get_value() and if the row index is not valid returns `InvalidCursorState`.  Let me know what you think.

2022-11-01 17:21 UTC, nbagnard commented on core/src/table_types.rs
> +            table_type: vec!["TABLE".to_string(), "VIEW".to_string()],
👍

2022-11-01 17:26 UTC, nbagnard commented on core/src/databases.rs
>      fn get_value(&self, col_index: u16) -> Result<Option<Bson>> {
Yes, it works :)

2022-11-01 17:26 UTC, nbagnard approved these changes
LGTM! 🎉

2022-11-01 17:52 UTC, pmeredit approved these changes
LGTM!

2022-11-01 18:29 UTC, bucaojit commented
evergreen merge

2022-11-01 18:50 UTC, merged