Sql 1168
mongodb/mongo-odbc-driver pull request #65
Opened 2023-01-12 21:56 UTC by terakilobyte

2023-01-19 02:42 UTC, terakilobyte commented on integration_test/tests/query_tests.rs
> +#[cfg(target_os = "linux")]
This test suite routinely segfaults on Windows. Attempting to troubleshoot this with @pmeredit led us to deciding to disable the test for Windows for now.

2023-01-20 17:35 UTC, pmeredit requested changes
Also, the double buffer change isn't in here. Perhaps this ticket should just be simplifying AnyOf anyway?

2023-01-20 17:35 UTC, pmeredit commented on core/src/json_schema.rs
> +                    ))
```suggestion
                    match any_of.len() {
                        0 => Err(Error::InvalidResultSetJsonSchema),
                         // if there is an AnyOf that contains one item, we can simplify it
                        1 => Schema::try_from(any_of.into_iter().next().unwrap()),
                        _ => Ok(Schema::AnyOf(
                            any_of
                                .into_iter()
                                .map(Atomic::try_from)
                                .collect::<Result<BTreeSet<Atomic>>>()?,
                        ))
                    }       
```

2023-01-20 17:35 UTC, pmeredit commented on core/src/json_schema.rs
> +                    ))
This cleans up the code a bit, imo.

2023-01-20 18:13 UTC, terakilobyte commented on core/src/json_schema.rs
> +                    ))
agreed, thanks for the suggesion!

2023-01-20 18:15 UTC, terakilobyte commented
@pmeredit Yeah we (@nbagnard and I) decided to remove that, as looking at it more closely we identified some issues with number of chars vs number of bytes, and decided to split that out into separate work.

2023-01-20 23:14 UTC, nbagnard approved these changes
LGTM! 👍

2023-01-21 00:49 UTC, pmeredit approved these changes
LGTM! Just make sure to change the commit message

2023-01-23 16:57 UTC, terakilobyte commented
evergreen merge

2023-01-23 18:05 UTC, pmeredit commented
evergreen merge

2023-01-23 18:06 UTC, merged